### ISSUE TITLE
Please restore build folder

### ISSUE THREAD

**Issue by AJenbo** [MrHuu/devilutionX-3ds#1]
since `build/.gitignore` has been deleted all builds are failing, please restore it so that we can see build status for the different platforms :)

https://github.com/MrHuu/devilutionX-3ds/commit/7597da1c0ff285d67d63c795979ee7fa68462796#diff-38dc90d020e872ead1c55faa51e9832c

**Comment by AJenbo** [comment]
Also why was mainmenu.cpp renamed to mmainmenu.cpp?

**Comment by MrHuu** [comment]
I'll have the build folder restored.

I'm not yet familiar with cmake. I chose to take the path i'm most familiar with, the regular makefile.
Creating / deleting the build folder is part of the current build instructions for 3ds.
I'll change the build folder for 3ds for now, to avoid conflicts with the proper cmake instructions.

The duplicate mainmenu.cpp was an other limitation of my knowledge.

All objects are currently being build (for 3ds) in the same folder without folder structure. Which has a conflict with these files:
- /Source/mainmenu.cpp
- /SourceX/DiabloUI/mainmenu.cpp

Renaming while building the object, like the switch port did, was an option.

But, since i was completely in the blank about getting this even running, i didn't want to spent much time looking into it.
I rather use the time for researching cmake to properly include the 3ds build instructions, which also solves the issue.

Thanks for your interest and time to look at the few changes made.
Not being a developer, i'm sure you'll notice a few more questionable changes.
Please, feel free to ask or laugh about them.

**Comment by AJenbo** [comment]
Nice work getting it running on 3DS, it's good to see that only a minimal amount of changes where needed and you maintained it as a fork so upstraming will be much easier the the Switch port 😊

It looks like you need to also hide romfsExit() and it's related code in main.cpp from other targets before they will build again.

**Comment by MrHuu** [comment]
To me it's unexpected how well the current build runs on a New3DS. All thanks to the progress made on devilution. So it's hats off to you sir, and others involved.

I also noticed, romfsExit() isn't even reached after return.
The current build freezes the 3ds upon shutdown, that's something i also need to fix.
Starting with my own oversights.

**Comment by AJenbo** [comment]
Looks like you more or less got the CMake stuff done in just one day, pretty impressive :)

We left you a couple of comments in the preliminery PR in case you didn't notice:
https://github.com/diasurgical/devilutionX/pull/483

**Comment by AJenbo** [comment]
Grate most targets are now building (Windows is currently failing to build stormlib)
